routes/web.php
                Route::get('country_data/show-tehsil/{id?}', 'CountryDataController@showTehsil')->name('country_data.showTehsil');
                Route::get('country_data/show-village/{id?}', 'CountryDataController@showVillage')->name('country_data.showVillage');
                //Route::get('country_data/destroy-village/{id?}', 'CountryDataController@destroyVillage')->name('country_data.destroyVillage');
                Route::get('checkDistrictname', 'CountryDataController@checkDistrictname')->name('country_data.checkDistrictname');
                Route::get('checkEditDistrictname', 'CountryDataController@checkEditDistrictname')->name('country_data.checkEditDistrictname');
                Route::get('checkTehsilname', 'CountryDataController@checkTehsilname')->name('country_data.checkTehsilname');
                Route::get('checkEditTehsilname', 'CountryDataController@checkEditTehsilname')->name('country_data.checkEditTehsilname');
                Route::get('checkVillagename', 'CountryDataController@checkVillagename')->name('country_data.checkVillagename');
                Route::get('checkEditVillagename', 'CountryDataController@checkEditVillagename')->name('country_data.checkEditVillagename');
                Route::post('destroy/{id}', 'CountryDataController@destroy')->name('country_data.destroy');
                Route::post('destroydistrict/{id}', 'CountryDataController@destroydistrict')->name('country_data.destroydistrict');
                Route::post('destroytehsil/{id}', 'CountryDataController@destroytehsil')->name('country_data.destroytehsil');
                Route::post('country_data/destroyvillage/{id}', 'CountryDataController@destroyvillage')->name('country_data.destroyvillage');
                Route::post('getCity', 'CountryDataController@getCity')->name('country_data.getCity');
                Route::post('getTehsil', 'CountryDataController@getTehsil')->name('country_data.getTehsil');
                Route::get('createVillage','CountryDataController@createVillage')->name('country_data.createVillage');
                Route::get('createCity','CountryDataController@createCity')->name('country_data.createCity');
                Route::post('state-store','CountryDataController@stateStore')->name('country_data.state_store');
                
                // Disritct
                Route::get('disritct-edit/{id}','CountryDataController@disritctEdit')->name('country_data.disritct_edit');
                Route::post('disritct-update','CountryDataController@disritctUpdate')->name('country_data.disritct_update');
                
                // Edit Tehsil
                Route::get('tehsil-edit/{id}','CountryDataController@tehsilEdit')->name('country_data.tehsil_edit');
                Route::post('tehsil-store','CountryDataController@tehsilStore')->name('country_data.update_tehsil');
                
                // Village
                Route::get('village-edit/{id}','CountryDataController@villageEdit')->name('country_data.village_edit');
                Route::post('village-update','CountryDataController@villageUpdate')->name('country_data.village_update');
                
                
            });

            Route::namespace('Priorities')->group(function () {
                Route::resource('pro_priority', 'PriorityController');
                // Route::post('update', 'PriorityController@update');
                Route::post('pro_priority/sort', 'PriorityController@cat_sort')->name('priority.sort');
                Route::post('pro_priority/subcat_sort', 'PriorityController@subcat_sort')->name('priority.subcat_sort');
                Route::post('pro_priority/getProduct', 'PriorityController@getProduct')->name('priority.getProduct');
                Route::post('pro_priority/getCategoryProduct', 'PriorityController@getCategoryProduct')->name('priority.getCategoryProduct');
                Route::post('pro_priority/getAllProduct', 'PriorityController@getAllProduct')->name('priority.getAllProduct');
            });
            Route::namespace('Users')->group(function () {
                Route::get('users', 'UsersController@index')->name('users.index');
                Route::get('users/create', 'UsersController@create')->name('users.create');
                Route::get('users/edit/{id}', 'UsersController@edit')->name('users.edit');
                Route::post('users/store', 'UsersController@store')->name('users.store');
                Route::post('users/destroy/{id}', 'UsersController@destroy')->name('users.destroy');
            });
            Route::namespace('Offers')->group(function () {
                Route::resource('offers', 'OffersController');
                Route::get('offers_product','OffersController@getProduct')->name('offers.product.attr');
                Route::post('offers/{id}', 'OffersController@update')->name('offers.update');
                Route::get('remove-image-offer', 'OffersController@removeImage')->name('offers.remove.image');
            });
            Route::namespace('Categories')->group(function () {
                Route::resource('categories', 'CategoryController');
                Route::get('remove-image-category', 'CategoryController@removeImage')->name('category.remove.image');
            });
            Route::namespace('Orders')->group(function () {
                Route::get('orders/printorder','OrderController@printInvoice')->name('orders.print_invoice');
                Route::resource('orders', 'OrderController');
                Route::resource('order-statuses', 'OrderStatusController');
                Route::get('orders/{id}/invoice', 'OrderController@generateInvoice')->name('orders.invoice.generate');
                Route::post('orders/print_order', 'OrderController@orderPrint')->name('orders.print_order');
            });
            Route::resource('addresses', 'Addresses\AddressController');
            Route::resource('countries', 'Countries\CountryController');
            Route::resource('countries.provinces', 'Provinces\ProvinceController');
            Route::resource('countries.provinces.cities', 'Cities\CityController');
            Route::resource('couriers', 'Couriers\CourierController');
            Route::resource('attributes', 'Attributes\AttributeController');
            Route::resource('attributes.values', 'Attributes\AttributeValueController');
            Route::resource('brands', 'Brands\BrandController');
            
            Route::get('list-customer', 'Wallet\WalletController@index')->name('wallet.index');
            Route::get('wallet-show/{id}', 'Wallet\WalletController@walletSummery')->name('wallet.show');

        // });
        //Changed the employees to companies
        // Route::group(['middleware' => ['role:admin|superadmin, guard:employee']], function () {
            Route::resource('companies', 'CompaniesController');
            Route::get('companies/{id}/profile', 'CompaniesController@getProfile')->name('companies.profile');
            Route::get('remove-logo', 'CompaniesController@removeLogo')->name('company.remove.logo');
            
             Route::get('checksearch','CompaniesController@checkSearch')->name('companies.checksearch');
            Route::get('changeStatus', 'CompaniesController@changeStatus')->name('companies.status');
            Route::get('checkCompanyname', 'CompaniesController@checkCompanyname')->name('companies.checkCompanyname');
            Route::get('checkEditCompanyname', 'CompaniesController@checkEditCompanyname')->name('companies.checkEditCompanyname');
            Route::put('companies/{id}/profile', 'CompaniesController@updateProfile')->name('companies.profile.update');
           
            Route::resource('roles', 'Roles\RoleController');
            Route::resource('permissions', 'Permissions\PermissionController');
        // });
    });
    Route::get('translate','Admin\TranslateController@translate')->name('translate');
});

/**
 * Frontend routes
 */
Auth::routes();
Route::namespace('Auth')->group(function () {
    Route::get('cart/login', 'CartLoginController@showLoginForm')->name('cart.login');
    Route::post('cart/login', 'CartLoginController@login')->name('cart.login');
    Route::get('logout', 'LoginController@logout');
});

Route::namespace('Front')->group(function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::group(['middleware' => ['auth', 'web']], function () {
        
        //contact
        Route::post('contact', 'HomeController@contactFormSubmit')->name('contact.contactFormSubmit');

        Route::namespace('Payments')->group(function () {
            Route::get('bank-transfer', 'BankTransferController@index')->name('bank-transfer.index');
            Route::post('bank-transfer', 'BankTransferController@store')->name('bank-transfer.store');
        });

        Route::namespace('Addresses')->group(function () {
            Route::resource('country.state', 'CountryStateController');
            Route::resource('state.city', 'StateCityController');
        });

        Route::get('accounts', 'AccountsController@index')->name('accounts');
        Route::get('checkout', 'CheckoutController@index')->name('checkout.index');
        Route::post('checkout', 'CheckoutController@store')->name('checkout.store');
        Route::get('checkout/execute', 'CheckoutController@executePayPalPayment')->name('checkout.execute');
        Route::post('checkout/execute', 'CheckoutController@charge')->name('checkout.execute');
        Route::get('checkout/cancel', 'CheckoutController@cancel')->name('checkout.cancel');
        Route::get('checkout/success', 'CheckoutController@success')->name('checkout.success');
        Route::resource('customer.address', 'CustomerAddressController');
    });
    Route::resource('cart', 'CartController');
    Route::get("category/{slug}", 'CategoryController@getCategory')->name('front.category.slug');

resources/views/admin/order-statuses/create.blade.php
@extends('layouts.admin.app')

@section('content')
    <!-- Main content -->
    <section class="content">

        @include('layouts.errors-and-messages')
        <!-- Default box -->
        <div class="box">
            <form action="{{ route('admin.order-statuses.store') }}" id="add_order_status" method="post">
            <div class="box-body">
                <h2>Order Status</h2>
                {{ csrf_field() }}
                <div class="form-group">
                    <label for="name">Name</label>
                    <input class="form-control" type="text" name="name" id="name" value="{{ old('name') }}" placeholder="Name" maxlength="25">
                </div>
                <div class="form-group">
                    <label for="color">Color</label>
                    <input class="form-control jscolor" type="text" name="color" id="color" value="{{ old('color') }}" maxlength="15">
                </div>
            </div>
            <!-- /.box-body -->
                <div class="box-footer btn-group">
                    <a href="{{ route('admin.order-statuses.index') }}" class="btn btn-default">Back</a>
                    <button type="submit" class="btn btn-primary">Create</button>
                </div>
            </form>
        </div>
        <!-- /.box -->
    </section>
    <!-- /.content -->
@endsection
@section('js')
    <script src="{{ asset('js/jscolor.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('js/jquery.validate.js') }}"></script>
    <script src="{{ asset('js/jquery.validate.min.js') }}"></script>
    <script src="{{ asset('js/additional-methods.min.js') }}"></script>
    <script type="text/javascript">
        $("#add_order_status").validate({
            ignore: [],
            errorClass: 'error',
            successClass: 'validation-valid-label',
            highlight: function(element, errorClass) {
                $(element).removeClass(errorClass);
            },
            unhighlight: function(element, errorClass) {
                $(element).removeClass(errorClass);
            },
            validClass: "validation-valid-label",
            rules: {
                name: {
                    required: true,
                    maxlength: 25,
                },
                color: {
                    required: true,
                    maxlength: 15,
                }
            },
            messages: {
                "name":{
                    required: "Please enter name.",
                    maxlength: "Please enter max 25 character",
                },
                "color":{
                    required: "Please enter color.",
                    maxlength: "Please enter max 15 character",
                }
            },
            submitHandler: function(form) {
                console.log('enter');
                $('button[type="submit"]').attr('disabled', true);
                form.submit();
            },
        });
    </script>
@endsection

resources/views/admin/order-statuses/edit.blade.php
@extends('layouts.admin.app')

@section('content')
    <!-- Main content -->
    <section class="content">

        @include('layouts.errors-and-messages')
        <!-- Default box -->
        <div class="box">
            <div class="box-body">
                <div class="box-header with-border bg-title border-header">
                    <h4 class="page-title header-color">Edit Status</h4>
                </div>
            </div>
            <div class="box-body">
                <form action="{{ route('admin.order-statuses.update', $orderStatus->id) }}" method="post" id="edit_order_status">
            <div class="box-body">
                {{ csrf_field() }}
                <input type="hidden" name="_method" value="put">
                <div class="row">
                    <div class="col-sm-6 col-md-5 col-sm-6 col-xs-12">
                        <div class="form-group">
                            <label for="name">Name <span class="text-danger">*</span></label>
                            <input class="form-control character" type="text" name="name" id="name" value="{{ $orderStatus->name ?: old('name') }}" placeholder="Name" maxlength="25">
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-5 col-sm-6 col-xs-12">
                        <div class="form-group">
                            <label for="display_name">Display Name <span class="text-danger">*</span></label>
                            <input class="form-control character" type="text" name="display_name" id="display_name" value="{{ $orderStatus->display_name ?: old('display_name') }}" placeholder="Display Name" maxlength="25">
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.box-body -->
                <div class="box-footer btn-group">
                    <a href="{{ route('admin.order-statuses.index') }}" class="btn btn-default">Cancel</a>
                    <button type="submit" class="btn btn-primary">Update</button>
                </div>
            </form>
            </div>
        </div>
        <!-- /.box -->
    </section>
    <!-- /.content -->
@endsection
@section('js')
    <script src="{{ asset('js/jscolor.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('js/jquery.validate.js') }}"></script>
    <script src="{{ asset('js/jquery.validate.min.js') }}"></script>
    <script src="{{ asset('js/additional-methods.min.js') }}"></script>
    <script type="text/javascript">
        $("#edit_order_status").validate({
            ignore: [],
            errorClass: 'error',
            successClass: 'validation-valid-label',
            highlight: function(element, errorClass) {
                $(element).removeClass(errorClass);
            },
            unhighlight: function(element, errorClass) {
                $(element).removeClass(errorClass);
            },
            validClass: "validation-valid-label",
            rules: {
                name: {
                    required: true,
                    maxlength: 25,
                },
                color: {
                    required: true,
                    maxlength: 15,
                }
            },
            messages: {
                "name":{
                    required: "Please enter name.",
                    maxlength: "Please enter max 25 character",
                },
                "color":{
                    required: "Please enter color.",
                    maxlength: "Please enter max 15 character",
                }
            },
            submitHandler: function(form) {
                $('button[type="submit"]').attr('disabled', true);
                form.submit();
            },
        });
        
        $('.character').on('input', function (event) {
            this.value = this.value.replace(/[^0-9\.\a-z\A-Z\@ _()$&]/g, '');
        });
    </script>
@endsection

resources/views/admin/order-statuses/list.blade.php
@extends('layouts.admin.app')

@section('content')
    <!-- Main content -->
    <section class="content">

        @include('layouts.errors-and-messages')
        <!-- Default box -->
        @if($orderStatuses)
        <div class="box">
            <div class="box-body">
                <div class="box-body">
                    <div class="box-header with-border bg-title border-header">
                        <h4 class="page-title header-color">Manage Order Status</h4>
                    </div>
                </div>
                <div class="box-body">
                    <table class="table border-b1px" id="table-id">
                    <thead>
                        <tr>
                            <th class="col-md-4">Name</th>
                            <th class="col-md-4">Color</th>
                            <th class="col-md-4">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach ($orderStatuses as $status)
                        <tr>
                            <td>{{ ucfirst($status->name) }}</td>
                            <td><button class="btn" style="background-color: {{ $status->color }}"><i class="fa fa-check" style="color: #ffffff"></i></button></td>
                            <td>
                                <form action="{{ route('admin.order-statuses.destroy', $status->id) }}" method="post" class="form-horizontal">
                                    {{ csrf_field() }}
                                    <input type="hidden" name="_method" value="delete">
                                    <div class="btn-group">
                                        @if($permission->edit==1)
                                            <a href="{{ route('admin.order-statuses.edit', $status->id) }}" class="btn btn-primary btn-sm"><i class="fa fa-pencil"></i> </a>
                                        @endif
                                    </div>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                </div>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                <div class="btn-group">
                </div>
            </div>
        </div>
        <!-- /.box -->
        @else
            <div class="box">
                <div class="box-body"><p class="alert alert-warning">No order status found.</p></div>
                <div class="box-footer">
                    <div class="btn-group">
                    </div>
                </div>
            </div>
        @endif

    </section>
    <!-- /.content -->
@endsection

@section('js')
<script>
    $(document).ready(function() {
        $('#table-id').DataTable();
    } );
</script>
@endsection